{% set python_min = '3.10.0' %}
{% set name = "poltergeist" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/poltergeist-{{ version }}.tar.gz
  sha256: bd9b6fb3d3ec07977ebe81fddd25b05ac21fc07989c7fc7afeb6307be759a0d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0

test:
  imports:
    - poltergeist
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alexandermalyga/poltergeist
  summary: Rust-like error handling in Python, with type-safety in mind.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
